"""
GOBNILP interface for Integer Programming Approach (IPA) structure learning.

This module provides interfaces to GOBNILP for structure learning.
Note: These functions require external binaries/tools to be installed.
"""

import os
import subprocess
import tempfile
from typing import Optional

import numpy as np


def run_gobnilp(
    scores_path: str,
    gobnilp_path: Optional[str] = None,
    output_path: Optional[str] = None
) -> np.ndarray:
    """
    Run GOBNILP optimizer and extract adjacency matrix.

    This function calls the GOBNILP binary on a precomputed scores file
    and extracts the resulting adjacency matrix.

    Note: This function requires GOBNILP to be installed and configured.
    See https://bitbucket.org/jamescussens/gobnilp for installation instructions.

    Parameters
    ----------
    scores_path : str
        Path to the scores file (Jaakkola format).
    gobnilp_path : str, optional
        Full path to the GOBNILP binary executable. If not provided,
        the function will look for 'gobnilp' in the system PATH.
    output_path : str, optional
        Path to the output file for the adjacency matrix. If not provided,
        a temporary file will be used.

    Returns
    -------
    np.ndarray
        Binary adjacency matrix representing the learned DAG.

    Raises
    ------
    FileNotFoundError
        If GOBNILP binary is not found.
    RuntimeError
        If GOBNILP execution fails or adjacency matrix is not generated.
    NotImplementedError
        If GOBNILP functionality is not available (check installation).
    """
    # Check if GOBNILP path is provided
    if gobnilp_path is None:
        # Try to find gobnilp in PATH
        gobnilp_path = _find_gobnilp_in_path()
        if gobnilp_path is None:
            raise NotImplementedError(
                "GOBNILP binary not found. "
                "Please install GOBNILP from https://bitbucket.org/jamescussens/gobnilp "
                "and either provide the path via gobnilp_path parameter or ensure "
                "'gobnilp' is in your system PATH."
            )

    # Check if gobnilp_path exists
    if not os.path.exists(gobnilp_path):
        raise FileNotFoundError(f"GOBNILP binary not found at: {gobnilp_path}")

    # Check if scores file exists
    if not os.path.exists(scores_path):
        raise FileNotFoundError(f"Scores file not found: {scores_path}")

    # Create temporary set file if output_path not provided
    if output_path is None:
        temp_output = tempfile.NamedTemporaryFile(mode='w', suffix='.mat', delete=False)
        output_path = temp_output.name
        temp_output.close()

    # Create set file with output path
    setfile = tempfile.NamedTemporaryFile(mode='w', suffix='.set', delete=False)
    setfile.write(f'gobnilp/outputfile/adjacencymatrix = "{output_path}"\n')
    setfile.close()

    try:
        # Run GOBNILP
        cmd = [gobnilp_path, '-f=jkl', '-v=2', f'-g={setfile.name}', scores_path]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=3600  # 1 hour timeout
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"GOBNILP execution failed with return code {result.returncode}.\n"
                f"Error output: {result.stderr}"
            )

        # Check if output file was generated
        if not os.path.exists(output_path):
            raise RuntimeError(
                "Adjacency matrix not generated by GOBNILP. "
                "Check GOBNILP output for errors."
            )

        # Read adjacency matrix
        try:
            adj_mat = np.loadtxt(output_path)
        except Exception as e:
            raise RuntimeError(
                f"Failed to read adjacency matrix from {output_path}: {e}"
            )

        # Clean up temporary files
        if os.path.exists(setfile.name):
            os.unlink(setfile.name)

        return adj_mat

    except subprocess.TimeoutExpired:
        raise RuntimeError("GOBNILP execution timed out (>1 hour).")

    except Exception:
        # Clean up on error
        if os.path.exists(setfile.name):
            os.unlink(setfile.name)
        raise


def _find_gobnilp_in_path() -> Optional[str]:
    """
    Try to find GOBNILP binary in system PATH.

    Returns
    -------
    str or None
        Path to gobnilp binary if found, None otherwise.
    """
    import shutil

    gobnilp_name = 'gobnilp'
    if os.name == 'nt':  # Windows
        gobnilp_name = 'gobnilp.exe'

    gobnilp_path = shutil.which(gobnilp_name)
    return gobnilp_path

